#!/usr/bin/env node
const fs=require('node:fs');const path=require('node:path');const {spawn}=require('node:child_process');const {createHash}=require('node:crypto');
function parseArgs(argv){const out={quality:null,device:'auto',overwrite:false};for(let i=0;i<argv.length;i++){const key=argv[i];if(key==='--help'||key==='-h'){out.help=true;continue;}if(key==='--overwrite'){out.overwrite=true;continue;}if(!['--job','--output','--blender','--quality','--device'].includes(key)||!argv[i+1]||argv[i+1].startsWith('--'))throw Error('Unknown argument or missing value: '+key);out[key.slice(2)]=argv[++i];}if(!out.help&&!out.job)throw Error('--job is required.');if(!['auto','cpu','cuda','optix'].includes(out.device))throw Error('Unsupported device.');if(out.quality&&!['smoke','draft','balanced','final'].includes(out.quality))throw Error('Unsupported quality.');return out;}
function findBlender(explicit){if(explicit||process.env.BLENDER_PATH)return explicit||process.env.BLENDER_PATH;if(process.platform==='win32'){const root=path.join(process.env.ProgramFiles||'C:\\Program Files','Blender Foundation');if(fs.existsSync(root)){for(const dir of fs.readdirSync(root).sort((a,b)=>b.localeCompare(a,undefined,{numeric:true}))){const executable=path.join(root,dir,'blender.exe');if(fs.existsSync(executable))return executable;}}}return 'blender';}
async function main(argv){
 const options=parseArgs(argv);if(options.help){console.log('Usage: node scripts/blender-render.cjs --job render-job.json [--output folder] [--blender executable] [--quality draft|balanced|final|smoke] [--device auto|cpu|cuda|optix] [--overwrite]');return;}
 const {validateRenderJob}=await import('../src/home/renderJob.mjs');const jobPath=path.resolve(options.job);if(fs.statSync(jobPath).size>5_000_000)throw Error('Job manifest too large.');const job=validateRenderJob(JSON.parse(fs.readFileSync(jobPath,'utf8')));
 const scene=path.join(path.dirname(jobPath),job.sceneFile);if(fs.statSync(scene).size>300_000_000)throw Error('Scene exceeds 300 MB.');const bytes=fs.readFileSync(scene);if(bytes.toString('ascii',0,4)!=='glTF'||bytes.readUInt32LE(4)!==2)throw Error('Expected a GLB 2.0 scene.');if(createHash('sha256').update(bytes).digest('hex')!==job.sceneSha256)throw Error('Scene checksum mismatch.');
 const output=path.resolve(options.output||path.join(path.dirname(jobPath),'output'));fs.mkdirSync(output,{recursive:true});if(!options.overwrite&&['render.png','scene.blend','render-report.json'].some(name=>fs.existsSync(path.join(output,name))))throw Error('Output already exists. Use a new folder or --overwrite.');
 const script=path.resolve(__dirname,'../../blender/render_home_interior.py');const executable=findBlender(options.blender);
 const args=['--background','--factory-startup','--disable-autoexec','--python-exit-code','1','--python',script,'--','--job',jobPath,'--output',output,'--quality',options.quality||job.quality,'--device',options.device];
 if(options.overwrite)args.push('--overwrite');console.log('Starting Blender:',executable,'Output:',output);
 await new Promise((resolve,reject)=>{const child=spawn(executable,args,{stdio:'inherit',shell:false,windowsHide:true});child.once('error',e=>reject(Error(`Could not start Blender. Set BLENDER_PATH or --blender. ${e.message}`)));child.once('exit',(code,signal)=>code===0?resolve():reject(Error(`Blender exited with ${code??signal}`)));});
 if(!fs.existsSync(path.join(output,'render.png')))throw Error('Blender completed without a PNG.');console.log('Render ready:',path.join(output,'render.png'));
}
module.exports={parseArgs,findBlender};if(require.main===module)main(process.argv.slice(2)).catch(e=>{console.error(e.message);process.exitCode=1;});
