import test from 'node:test';import assert from 'node:assert/strict';
import {DEFAULT_LIGHTING,validateLighting,lightingAt,kelvinRgb,ROOM_LIGHTING,LAYERS} from '../src/home/lighting.mjs';
import {HOME_ROOMS} from '../src/home/rooms.mjs';
test('every named room has a layered lighting proposal',()=>{assert.deepEqual(Object.keys(ROOM_LIGHTING),HOME_ROOMS.map(r=>r.id));for(const p of Object.values(ROOM_LIGHTING))for(const point of [p.task,p.cabinet])assert.ok(point.every(n=>n>=0&&n<=1));});
test('auto schedule handles boundaries and midnight, cooler day warmer night',()=>{const s=validateLighting(DEFAULT_LIGHTING);assert.equal(lightingAt(s,'entry',7).mode,'day');assert.equal(lightingAt(s,'entry',18).mode,'evening');assert.equal(lightingAt(s,'entry',21).mode,'night');assert.equal(lightingAt(s,'entry',0).kelvin,2700);assert.equal(lightingAt(s,'entry',12).kelvin,4500);});
test('room overrides and individual layer switches do not leak to other rooms',()=>{const s=structuredClone(DEFAULT_LIGHTING);s.rooms.kitchen={mode:'night',layers:{cabinet:false}};const c=validateLighting(s);assert.equal(lightingAt(c,'kitchen',12).levels.cabinet,0);assert.equal(lightingAt(c,'entry',12).mode,'day');assert.ok(lightingAt(c,'kitchen',12).levels.task>0);});
test('invalid lighting parameters are rejected',()=>{for(const change of [s=>s.mode='laser',s=>s.intensity=Infinity,s=>s.intensity=-1,s=>s.schedule.nightStart=6,s=>s.rooms.unknown={},s=>s.layers.cabinet='false',s=>s.rooms.entry={kelvin:'hot'}]){const s=structuredClone(DEFAULT_LIGHTING);change(s);assert.throws(()=>validateLighting(s));}});
test('all layers can be independently disabled and master intensity scales them',()=>{for(const layer of LAYERS){const s=structuredClone(DEFAULT_LIGHTING);s.layers[layer]=false;assert.equal(lightingAt(validateLighting(s),'study',12).levels[layer],0);}const s=validateLighting({...DEFAULT_LIGHTING,intensity:0});assert.ok(Object.values(lightingAt(s,'study',12).levels).every(v=>v===0));});
test('Kelvin approximation is bounded and night contains less blue',()=>{const warm=kelvinRgb(2700),day=kelvinRgb(4500);assert.ok(warm[2]<day[2]);for(const k of [1000,2700,4500,6500,12000])assert.ok(kelvinRgb(k).every(x=>x>=0&&x<=1));assert.throws(()=>kelvinRgb(NaN));});
