import React,{useState,useSyncExternalStore} from 'react';
import {getInteriorScenes,subscribeScenes} from '../render/interiorScene.js';
export default function BlenderPanel(){
 const available=useSyncExternalStore(subscribeScenes,()=>JSON.stringify(getInteriorScenes().map(r=>({id:r.id,ready:r.ready}))));
 const [quality,setQuality]=useState('balanced'),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const scenes=JSON.parse(available);
 return <section aria-label="Blender rendering"><h3>Render the actual scene in Blender</h3><p>The browser exports a GLB with local PBR textures, the current camera and per-room light fixtures. Blender runs as a separate program on your machine; it is not embedded as a DLL, and this page cannot start local programs.</p>
 <label>Render quality<select aria-label="Render quality" value={quality} onChange={e=>setQuality(e.target.value)}><option value="draft">Draft · 960 px / 32 samples</option><option value="balanced">Balanced · 1600 px / 128 samples</option><option value="final">Final · 2560 px / 512 samples</option></select></label>
 {scenes.length?scenes.map(r=><button key={r.id} disabled={busy||!r.ready} onClick={async()=>{setBusy(true);setMessage('Preparing geometry and textures…');try{const {downloadBlenderBundle}=await import('../render/blenderExport.js');const job=await downloadBlenderBundle(r.id,{quality,onProgress:setMessage});setMessage(`Exported ${job.meshCount} meshes and ${job.fixtures.length} layer fixtures. Extract the ZIP and run the command below.`);}catch(e){setMessage(e.message);}finally{setBusy(false);}}}>Export {r.id} for Blender</button>):<p>Open a room’s 3D view first, position the camera, then return here.</p>}
 <p role="status">{message}</p><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>node react-configurator/scripts/blender-render.cjs --job "C:\Renders\entry\render-job.json" --output "C:\Renders\entry\output"</pre>
 <p>Set <code>BLENDER_PATH</code> to Blender’s executable, or pass <code>--blender</code>. The runner also checks standard Windows installation folders. Outputs are a PNG, editable .blend scene and a render report. Existing outputs are protected unless you explicitly pass <code>--overwrite</code>.</p><p>The export preserves the currently visible/cutaway geometry. Orthographic overview and perspective room cameras are supported. Blender improves indirect bounce and area-light shadows; model detail and camera composition still determine final realism.</p>
 </section>;
}
